### ISSUE TITLE
Exception thrown when using some loading spins

### ISSUE THREAD

**Issue by kennethnym** [jogboms/flutter_spinkit#49]
**Describe the bug**
The following exception:
```
2019-03-12 17:00:06.281 9687-9758/com.anticus.crossservice_mobile I/flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
2019-03-12 17:00:06.281 9687-9758/com.anticus.crossservice_mobile I/flutter: The following assertion was thrown during performLayout():
2019-03-12 17:00:06.281 9687-9758/com.anticus.crossservice_mobile I/flutter: 'package:flutter/src/painting/alignment.dart': Failed assertion: line 530 pos 12: 'direction !=
2019-03-12 17:00:06.281 9687-9758/com.anticus.crossservice_mobile I/flutter: null': is not true.
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: more information in this error message to help you determine and fix the underlying cause.
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: In either case, please report this assertion by filing a bug on GitHub:
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: When the exception was thrown, this was the stack:
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #2      AlignmentDirectional.resolve (package:flutter/src/painting/alignment.dart:530:12)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #3      RenderStack._resolve (package:flutter/src/rendering/stack.dart:360:36)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #4      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:475:5)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #6      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #8      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #10     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #12     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #14     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.282 9687-9758/com.anticus.crossservice_mobile I/flutter: #16     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #18     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #22     RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #23     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #24     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #39     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #40     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: #41     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: (elided 10 frames from class _AssertionError and package dart:async)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: The following RenderObject was being processed when the exception was fired:
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   RenderStack#c7a6f NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   creator: Stack ← SizedBox ← Center ← SpinKitFadingCircle ← Padding ← Row ← Column ← Expanded ←
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   Column ← Padding ← ServicePicker ← DecoratedBox ← ⋯
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   parentData: <none> (can use size)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   constraints: BoxConstraints(w=50.0, h=50.0)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   size: MISSING
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   alignment: AlignmentDirectional.topStart
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   textDirection: null
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   fit: loose
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   overflow: clip
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: This RenderObject had the following descendants (showing up to depth 5):
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   RenderTransform#33f41 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:     RenderPositionedBox#e8cbf NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:       RenderAnimatedOpacity#063a0 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:         RenderConstrainedBox#c6af1 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:           RenderDecoratedBox#4ebec NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   RenderTransform#20025 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:     RenderPositionedBox#a047b NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:       RenderAnimatedOpacity#19cdf NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:         RenderConstrainedBox#f76fc NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:           RenderDecoratedBox#95b82 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   RenderTransform#397b0 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:     RenderPositionedBox#c0e0b NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:       RenderAnimatedOpacity#9e140 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:         RenderConstrainedBox#efe90 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:           RenderDecoratedBox#056e2 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   RenderTransform#2c907 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:     RenderPositionedBox#d68b6 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:       RenderAnimatedOpacity#ab386 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:         RenderConstrainedBox#3b729 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:           RenderDecoratedBox#88b79 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   RenderTransform#7ea6d NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:     RenderPositionedBox#46f1e NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:       RenderAnimatedOpacity#eda0e NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:         RenderConstrainedBox#8b604 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:           RenderDecoratedBox#72b36 NEEDS-LAYOUT NEEDS-PAINT
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter:   ...(descendants list truncated after 25 lines)
2019-03-12 17:00:06.283 9687-9758/com.anticus.crossservice_mobile I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2019-03-12 17:00:06.284 9687-9758/com.anticus.crossservice_mobile I/flutter: Another exception was thrown: RenderBox was not laid out: RenderStack#c7a6f NEEDS-PAINT
2019-03-12 17:00:06.284 9687-9758/com.anticus.crossservice_mobile I/flutter: Another exception was thrown: RenderBox was not laid out: RenderConstrainedBox#ef9c3 relayoutBoundary=up5 NEEDS-PAINT
2019-03-12 17:00:06.284 9687-9758/com.anticus.crossservice_mobile I/flutter: Another exception was thrown: RenderBox was not laid out: RenderPositionedBox#59ea0 relayoutBoundary=up4 NEEDS-PAINT
```
is thrown whenever I try to use some SpinKits.

**Steps to reproduce**
1. Create a new flutter project  
2. Replace the code with the following:
```import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.all(10),
      child: SpinKitFadingCircle(color: Colors.white),
    );
  }
}
```
3. Error is thrown.

**SpinKit name**
- DoubleBounce
- FadingFour
- FadingCube
- Pulse
- ChasingDot
- ThreeBounce
- Circle
- CubeGrid
- FadingCircle
- FoldingCube
- Ripple

**Comment by jogboms** [comment]
This is odd. I would take a look.

**Comment by jogboms** [comment]
@MrCreeper1008 sorry for the delay.
I have run the test and still couldn't reproduce what you are currently facing. Please try the example folder and see if it is reproducible there.
