### ISSUE TITLE
flutter analyze error 4.1.0: NoSuchMethodError: The method 'accept' was called on null.

### ISSUE THREAD

**Issue by masashi-sutou** [jogboms/flutter_spinkit#62]
## Describe the bug

I upgraded flutter_spinkit 4.1.0 from 4.0.0.
I run flutter analyze, and have following error.

<details>
<summary>error log</summary>

```
Running "flutter pub get" in my-app...                        8.5s
Analyzing my-app...
Error from the analysis server: Exception while using a PreferConstConstructors to visit a InstanceCreationExpressionImpl in ReturnStatementImpl in BlockImpl in BlockFunctionBodyImpl in MethodDeclarationImpl in ClassDeclarationImpl in CompilationUnitImpl

NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept<DartObjectImpl>(Instance of 'ConstantVisitor')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:717:53)
#2      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/dart/constant/constant_verifier.dart:134:27)
#3      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#4      LinterContextImpl._hasConstantVerifierError (package:analyzer/src/lint/linter.dart:322:10)
#5      LinterContextImpl.canBeConst (package:analyzer/src/lint/linter.dart:290:15)
#6      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/prefer_const_constructors.dart:95:19)
#7      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#8      LinterVisitor._runSubscriptions (package:analyzer/src/lint/linter_visitor.dart:713:14)
#9      LinterVisitor.visitInstanceCreationExpression (package:analyzer/src/lint/linter_visitor.dart:383:5)
#10     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6180:15)
#11     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8638:18)
#12     RecursiveAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:1164:10)
#13     LinterVisitor.visitReturnStatement (package:analyzer/src/lint/linter_visitor.dart:541:11)
#14     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8634:49)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#16     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1115:17)
#17     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:665:10)
#18     LinterVisitor.visitBlock (package:analyzer/src/lint/linter_visitor.dart:66:11)
#19     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1111:49)
#20     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1070:13)
#21     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:671:10)
#22     LinterVisitor.visitBlockFunctionBody (package:analyzer/src/lint/linter_visitor.dart:72:11)
#23     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1066:49)
#24     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7110:12)
#25     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1061:10)
#26     LinterVisitor.visitMethodDeclaration (package:analyzer/src/lint/linter_visitor.dart:450:11)
#27     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7101:49)
#28     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#29     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1584:13)
#30     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:701:10)
#31     LinterVisitor.visitClassDeclaration (package:analyzer/src/lint/linter_visitor.dart:102:11)
#32     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7670:20)
#34     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2161:21)
#35     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#36     LinterVisitor.visitCompilationUnit (package:analyzer/src/lint/linter_visitor.dart:126:11)
#37     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#38     LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:353:10)
#39     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:206:11)
#40     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#41     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:201:35)
#42     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:115:14)
#43     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#44     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:114:43)
#45     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1259:63)
#46     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#47     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#48     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1065:33)
<asynchronous suspension>
#49     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1921:24)
<asynchronous suspension>
#50     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1855:5)
#51     new AnalysisServer (package:analysis_server/src/analysis_server.dart:212:29)
#52     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#53     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#54     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:572:21)
#55     _rootRun (dart:async/zone.dart:1124:13)
#56     _CustomZone.run (dart:async/zone.dart:1021:19)
#57     _runZoned (dart:async/zone.dart:1516:10)
#58     runZoned (dart:async/zone.dart:1463:12)
#59     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:689:12)
#60     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:570:7)
#61     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474:9)
#62     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#63     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:469:43)
#64     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#65     new Future.sync (dart:async/future.dart:224:31)
#66     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#67     _rootRun (dart:async/zone.dart:1124:13)
#68     _CustomZone.run (dart:async/zone.dart:1021:19)
#69     _runZoned (dart:async/zone.dart:1516:10)
#70     runZoned (dart:async/zone.dart:1463:12)
#71     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#72     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
#73     Driver.start (package:analysis_server/src/server/driver.dart:469:21)
#74     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
#75     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#76     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
#77     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


Server error(s) occurred. (ran in 16.3s)
Exited with code 1
```
</details>

## workaround

I downgrade flutter_spinkit 4.0.0, so I have no error.

**Comment by jogboms** [comment]
Hey @masashi-sutou 

Can I see the output of `flutter doctor`?

Thanks

**Comment by masashi-sutou** [comment]
@jogboms 

<details>
<summary>flutter doctor</summary>

```
#!/bin/bash -eo pipefail
$FLUTTER_HOME/bin/flutter doctor
Downloading Dart SDK from Flutter engine b863200c37df4ed378042de11c4e9ff34e4e58c9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  264M  100  264M    0     0  97.2M      0  0:00:02  0:00:02 --:--:-- 97.2M
Building flutter tool...
Resolving dependencies... (1.0s)(1.1s)(1.2s)(1.3s)(1.4s)(1.5s)(1.6s)(1.7s)(1.8s)(1.9s)(2.0s)(2.1s)(2.2s)(2.3s)(2.4s)(2.5s)(2.6s)(2.7s)(2.8s)(2.9s)(3.0s)(3.1s)(3.2s)(3.3s)(3.4s)(3.5s)(3.6s)(3.7s)(3.8s)(3.9s)(4.0s)(4.1s)(4.2s)(4.3s)(4.4s)(4.5s)(4.6s)(4.7s)(4.8s)(4.9s)(5.0s)(5.1s)(5.2s)(5.3s)(5.4s)(5.5s)(5.6s)(5.7s)(5.8s)(5.9s)(6.0s)(6.1s)(6.6s)
+ analyzer 0.36.4 (0.39.1 available)
+ archive 2.0.10 (2.0.11 available)
+ args 1.5.2
+ async 2.3.0 (2.4.0 available)
+ bazel_worker 0.1.21 (0.1.23 available)
+ boolean_selector 1.0.5
+ browser_launcher 0.1.2 (0.1.5 available)
+ build 1.1.5 (1.2.2 available)
+ build_config 0.4.1+1
+ build_daemon 2.0.0 (2.1.2 available)
+ build_modules 2.4.2 (2.7.0 available)
+ build_resolvers 1.0.6 (1.3.0 available)
+ build_runner 1.6.5 (1.7.2 available)
+ build_runner_core 3.0.9 (4.2.0 available)
+ build_test 0.10.8 (0.10.10 available)
+ build_vm_compilers 1.0.2 (1.0.4 available)
+ build_web_compilers 2.2.2 (2.7.1 available)
+ built_collection 4.2.2 (4.3.0 available)
+ built_value 6.7.0 (7.0.0 available)
+ charcode 1.1.2
+ checked_yaml 1.0.2
+ code_builder 3.2.0 (3.2.1 available)
+ codemirror 0.5.7+5.48.0 (0.5.12+5.49.2 available)
+ collection 1.14.11 (1.14.12 available)
+ completion 0.2.1+1
+ convert 2.1.1
+ coverage 0.13.2 (0.13.3+1 available)
+ crypto 2.1.1+1 (2.1.3 available)
+ csslib 0.16.1
+ dart_style 1.2.9 (1.3.3 available)
+ devtools 0.1.1 (0.1.11 available)
+ devtools_server 0.1.2 (0.1.12 available)
+ dwds 0.5.0 (0.8.1 available)
+ file 5.0.8+1 (5.1.0 available)
+ file_testing 2.1.0
+ fixnum 0.10.9 (0.10.11 available)
+ flutter_goldens_client 0.0.0 from path ../flutter_goldens_client
+ front_end 0.1.19 (0.1.29 available)
+ glob 1.1.7 (1.2.0 available)
+ graphs 0.2.0
+ html 0.14.0+2 (0.14.0+3 available)
+ http 0.12.0+2
+ http_multi_server 2.1.0
+ http_parser 3.1.3
+ intl 0.15.8 (0.16.0 available)
+ io 0.3.3
+ js 0.6.1+1
+ json_annotation 3.0.0
+ json_rpc_2 2.1.0
+ kernel 0.3.19 (0.3.29 available)
+ linter 0.1.93 (0.1.104 available)
+ logging 0.11.3+2
+ matcher 0.12.5 (0.12.6 available)
+ meta 1.1.7 (1.1.8 available)
+ mime 0.9.6+3
+ mockito 4.1.0 (4.1.1 available)
+ multi_server_socket 1.0.2
+ multicast_dns 0.2.1 (0.2.2 available)
+ mustache 1.1.1
+ node_preamble 1.4.6 (1.4.8 available)
+ octicons_css 0.0.1
+ package_config 1.0.5 (1.1.0 available)
+ package_resolver 1.0.10
+ path 1.6.4
+ pedantic 1.8.0+1
+ petitparser 2.4.0
+ platform 2.2.1
+ platform_detect 1.3.5 (1.4.0 available)
+ plotly_js 0.0.1 (0.0.2 available)
+ plugin 0.2.0+3
+ polymer_css 0.0.1
+ pool 1.4.0
+ primer_css 0.0.2
+ process 3.0.11 (3.0.12 available)
+ protobuf 0.13.15 (1.0.1 available)
+ pub_semver 1.4.2
+ pubspec_parse 0.1.5
+ quiver 2.0.5 (2.1.2+1 available)
+ rxdart 0.21.0 (0.22.6 available)
+ scratch_space 0.0.4 (0.0.4+1 available)
+ shelf 0.7.5
+ shelf_packages_handler 1.0.4
+ shelf_proxy 0.1.0+7
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.3
+ source_map_stack_trace 1.1.5
+ source_maps 0.10.8
+ source_span 1.5.5
+ split 0.0.4 (0.0.7 available)
+ sse 2.0.2 (3.0.0 available)
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ stream_transform 0.0.19 (1.0.0 available)
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ test 1.6.3 (1.9.4 available)
+ test_api 0.2.5 (0.2.11 available)
+ test_core 0.2.5 (0.2.15 available)
+ timing 0.1.1+2
+ typed_data 1.1.6
+ usage 3.4.1
+ uuid 2.0.2 (2.0.4 available)
+ vm_service 1.1.0 (2.1.2 available)
+ vm_service_client 0.2.6+2 (0.2.6+3 available)
+ vm_service_lib 3.22.2+1
+ watcher 0.9.7+12 (0.9.7+13 available)
+ web_socket_channel 1.0.15 (1.1.0 available)
+ webkit_inspection_protocol 0.4.2 (0.5.0 available)
+ xml 3.5.0 (3.6.0 available)
+ yaml 2.1.16 (2.2.0 available)
Downloading build_test 0.10.8...
Downloading node_preamble 1.4.6...
Downloading build_vm_compilers 1.0.2...
Downloading shelf_packages_handler 1.0.4...
Downloading file_testing 2.1.0...
Downloading mockito 4.1.0...
Downloading collection 1.14.11...
Downloading multi_server_socket 1.0.2...
Downloading test 1.6.3...
Downloading build_runner 1.6.5...
Downloading yaml 2.1.16...
Downloading logging 0.11.3+2...
Downloading plotly_js 0.0.1...
Downloading sse 2.0.2...
Downloading archive 2.0.10...
Downloading usage 3.4.1...
Downloading plugin 0.2.0+3...
Downloading csslib 0.16.1...
Downloading devtools_server 0.1.2...
Downloading build_resolvers 1.0.6...
Downloading typed_data 1.1.6...
Downloading package_resolver 1.0.10...
Downloading source_maps 0.10.8...
Downloading source_span 1.5.5...
Downloading process 3.0.11...
Downloading completion 0.2.1+1...
Downloading bazel_worker 0.1.21...
Downloading json_rpc_2 2.1.0...
Downloading io 0.3.3...
Downloading test_core 0.2.5...
Downloading json_annotation 3.0.0...
Downloading xml 3.5.0...
Downloading charcode 1.1.2...
Downloading coverage 0.13.2...
Downloading http_multi_server 2.1.0...
Downloading path 1.6.4...
Downloading intl 0.15.8...
Downloading pubspec_parse 0.1.5...
Downloading glob 1.1.7...
Downloading pool 1.4.0...
Downloading html 0.14.0+2...
Downloading vm_service 1.1.0...
Downloading package_config 1.0.5...
Downloading build_web_compilers 2.2.2...
Downloading dwds 0.5.0...
Downloading vm_service_lib 3.22.2+1...
Downloading build_modules 2.4.2...
Downloading source_map_stack_trace 1.1.5...
Downloading boolean_selector 1.0.5...
Downloading build_runner_core 3.0.9...
Downloading matcher 0.12.5...
Downloading petitparser 2.4.0...
Downloading meta 1.1.7...
Downloading mustache 1.1.1...
Downloading shelf_static 0.2.8...
Downloading webkit_inspection_protocol 0.4.2...
Downloading timing 0.1.1+2...
Downloading graphs 0.2.0...
Downloading codemirror 0.5.7+5.48.0...
Downloading stream_transform 0.0.19...
Downloading multicast_dns 0.2.1...
Downloading fixnum 0.10.9...
Downloading convert 2.1.1...
Downloading stack_trace 1.9.3...
Downloading polymer_css 0.0.1...
Downloading rxdart 0.21.0...
Downloading crypto 2.1.1+1...
Downloading browser_launcher 0.1.2...
Downloading args 1.5.2...
Downloading front_end 0.1.19...
Downloading linter 0.1.93...
Downloading vm_service_client 0.2.6+2...
Downloading string_scanner 1.0.5...
Downloading js 0.6.1+1...
Downloading shelf 0.7.5...
Downloading term_glyph 1.1.0...
Downloading stream_channel 2.0.0...
Downloading shelf_web_socket 0.2.3...
Downloading pedantic 1.8.0+1...
Downloading devtools 0.1.1...
Downloading built_collection 4.2.2...
Downloading split 0.0.4...
Downloading http 0.12.0+2...
Downloading build_config 0.4.1+1...
Downloading uuid 2.0.2...
Downloading checked_yaml 1.0.2...
Downloading async 2.3.0...
Downloading dart_style 1.2.9...
Downloading primer_css 0.0.2...
Downloading analyzer 0.36.4...
Downloading test_api 0.2.5...
Downloading http_parser 3.1.3...
Downloading build 1.1.5...
Downloading pub_semver 1.4.2...
Downloading platform 2.2.1...
Downloading kernel 0.3.19...
Downloading build_daemon 2.0.0...
Downloading quiver 2.0.5...
Downloading watcher 0.9.7+12...
Downloading code_builder 3.2.0...
Downloading scratch_space 0.0.4...
Downloading mime 0.9.6+3...
Downloading platform_detect 1.3.5...
Downloading octicons_css 0.0.1...
Downloading web_socket_channel 1.0.15...
Downloading built_value 6.7.0...
Downloading shelf_proxy 0.1.0+7...
Downloading file 5.0.8+1...
Downloading protobuf 0.13.15...
Changed 110 dependencies!
Precompiling executables... (1.0s)(1.1s)(1.2s)(1.3s)(1.4s)(1.5s)(1.6s)(1.7s)(1.8s)(1.9s)(2.0s)(2.1s)(2.2s)(2.3s)(2.4s)(2.5s)
Precompiled completion:shell_completion_generator.
Precompiled coverage:run_and_collect.
Precompiled coverage:format_coverage.
Precompiled coverage:collect_coverage.
Precompiled kernel:count_breakdown.
Precompiled kernel:dump.
Precompiled kernel:split.
Precompiled kernel:size_breakdown.
Precompiled kernel:type_check.
Precompiled archive:tar.
Precompiled webkit_inspection_protocol:multiplex.
Precompiled devtools:devtools.
Precompiled kernel:transform.
Precompiled dart_style:format.
Precompiled linter:linter.
Precompiled build_runner:graph_inspector.
Precompiled test:test.
Precompiled build_runner:build_runner.
Downloading Material fonts...                                       0.3s
Downloading android-arm-profile/linux-x64 tools...                  0.2s
Downloading android-arm-release/linux-x64 tools...                  0.2s
Downloading android-arm64-profile/linux-x64 tools...                0.2s
Downloading android-arm64-release/linux-x64 tools...                0.2s
Downloading android-x86 tools...                                    0.6s
Downloading android-x64 tools...                                    0.5s
Downloading android-arm tools...                                    0.6s
Downloading android-arm-profile tools...                            0.3s
Downloading android-arm-release tools...                            0.3s
Downloading android-arm64 tools...                                  0.5s
Downloading android-arm64-profile tools...                          0.2s
Downloading android-arm64-release tools...                          0.2s
Downloading Gradle Wrapper...                                       0.1s
Downloading package sky_engine...                                   0.1s
Downloading common tools...                                         0.4s
Downloading common tools...                                         0.4s
Downloading linux-x64 tools...                                      1.0s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale C.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
</details>
