### ISSUE TITLE
Error: AnimationController not disposed, leak on the Ticker

### ISSUE THREAD

**Issue by GGLabCenter** [jogboms/flutter_spinkit#84]
Hi,

I got an error while using the lib.
Basically, I just put a loading Widget and then called a setstate() that would have cleaned it away. (upload view)

The main issue, it seems to me, is in this point of the source code, SpinKitPouringHourglass class:

```
  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
```
The controller seems not disposed, because the object containing the controller is disposed first (via super()). Maybe it should be:
```
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
```

Here is some log:

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
_SpinKitPouringHourglassState#e76fa(ticker active) was disposed with an active Ticker.

_SpinKitPouringHourglassState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: Ticker(created by _SpinKitPouringHourglassState#e76fa(lifecycle state: created))
The stack trace when the Ticker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
#2      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:131:15)
#3      new AnimationController (package:flutter/src/animation/animation_controller.dart:248:21)
#4      _SpinKitPouringHourglassState.initState (package:flutter_spinkit/src/pouring_hour_glass.dart:33:23)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
#9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5705:32)
#10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
#27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#32     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#36     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#41     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#47     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#54     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#59     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#63     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#72     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
#75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
#77     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
#78     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
#79     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
#80     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#81     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
#82     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
#86     _invoke (dart:ui/hooks.dart:251:10)
#87     _drawFrame (dart:ui/hooks.dart:209:3)
(elided 3 frames from dart:async)
When the exception was thrown, this was the stack
#0      SingleTickerProviderStateMixin.dispose.<anonymous closure>
package:flutter/…/widgets/ticker_provider.dart:144
#1      SingleTickerProviderStateMixin.dispose
package:flutter/…/widgets/ticker_provider.dart:158
#2      _SpinKitPouringHourglassState.dispose
package:flutter_spinkit/src/pouring_hour_glass.dart:52
#3      StatefulElement.unmount
package:flutter/…/widgets/framework.dart:4854
#4      _InactiveElements._unmount
package:flutter/…/widgets/framework.dart:1998
... infinite errors
```

**Comment by jogboms** [comment]
Could not reproduce this on v4.1.2+1. Could you verify and reopen if this is not the case?
